# ==============================================================
# Script 08d: Habitat Suitability Visualization
# Project: rumex-landscape-phylogenomics
#
# Produces publication-quality habitat suitability maps from the
# ensemble projection rasters generated by Script 08c. For each
# scenario, the continuous suitability raster is reclassified
# into three categories (Low / Medium / High suitability) and
# overlaid on a regional basemap with occurrence points.
#
# Thresholds operate on biomod2's 0-1000 suitability scale; the
# values below are tuned for the Himalaya-Hengduan study area
# and can be adjusted at the top of the script.
#
# Input
#   - One biomod2 ensemble projection raster (.tif)
#       e.g., rumex_EMmeanByROC_mergedData_mergedRun_mergedAlgo.tif
#   - Thinned occurrence CSV (Script 08a)
#
# Output
#   - <out_prefix>.png  (high-res, dpi=600)
#   - <out_prefix>.tiff (high-res, dpi=600)
#
# Dependencies: terra, sf, ggplot2, tidyterra, rnaturalearth,
#               rnaturalearthdata
# ==============================================================

# ----- USER CONFIGURATION -----
proj_raster_path <- "results/sdm/env/Current_autocorrelated/biomod_output/Current_EM/individual_projections/rumex_EMmeanByROC_mergedData_mergedRun_mergedAlgo.tif"
occ_csv          <- "results/sdm/occurrences/rumex_thinned.csv"
out_prefix       <- "figures/sdm/Current_Suitability"
plot_title       <- "Current (1990 - 2000)"
panel_label      <- "(a)"

# Suitability thresholds on biomod2's 0-1000 scale
not_suitable_max <- 50        # below this = transparent (not shown)
low_max          <- 300       # up to this = "Low"
medium_max       <- 700       # up to this = "Medium"; above = "High"

# Map extent and study-area countries (Himalaya-Hengduan region)
study_countries <- c("Nepal", "Bhutan", "India", "China", "Pakistan",
                     "Afghanistan", "Myanmar", "Bangladesh", "Tajikistan")
wide_bbox <- c(xmin = 62, xmax = 108, ymin = 10, ymax = 45)
view_xlim <- c(65, 106)
view_ylim <- c(20, 42)
# ------------------------------

library(ggplot2)
library(tidyterra)
library(terra)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

dir.create(dirname(out_prefix), recursive = TRUE, showWarnings = FALSE)

# --------------------------------------------------------------
# 1. Load data
# --------------------------------------------------------------
proj_raster <- rast(proj_raster_path)

occ_data <- read.csv(occ_csv)
occ_data$Longitude <- as.numeric(occ_data$Longitude)
occ_data$Latitude  <- as.numeric(occ_data$Latitude)
occ_data <- occ_data[!duplicated(occ_data[, c("Longitude","Latitude")]), ]

# --------------------------------------------------------------
# 2. Build country basemap and study-area mask
# --------------------------------------------------------------
world <- ne_countries(scale = "medium", returnclass = "sf")
world <- st_make_valid(world)
world <- world[!st_is_empty(world), ]

study_region <- st_union(world[world$name %in% study_countries, ])
study_vect   <- vect(study_region)

# --------------------------------------------------------------
# 3. Mask projection and reclassify into 3 suitability categories
# --------------------------------------------------------------
proj_masked <- mask(proj_raster, study_vect)
proj_masked[proj_masked <= not_suitable_max] <- NA   # hide "not suitable"

rcl_matrix <- matrix(c(
    not_suitable_max, low_max,    1,    # Low
    low_max,          medium_max, 2,    # Medium
    medium_max,       Inf,        3     # High
), ncol = 3, byrow = TRUE)
suit_raster <- classify(proj_masked, rcl_matrix)

# Convert to factor with descriptive labels
labels_vec <- c(
    paste0("Low Suitable (<", round(low_max/10), "%)"),
    paste0("Medium Suitable (", round(low_max/10), "-", round(medium_max/10), "%)"),
    paste0("High Suitable (>", round(medium_max/10), "%)")
)
levels(suit_raster) <- data.frame(id = 1:3, label = labels_vec)

# Wider basemap clipped to a viewing bounding box
wide_bbox_sfc  <- st_as_sfc(st_bbox(wide_bbox, crs = st_crs(4326)))
countries_wide <- st_intersection(st_make_valid(world), wide_bbox_sfc)

# --------------------------------------------------------------
# 4. Plot
# --------------------------------------------------------------
p <- ggplot() +
    geom_sf(data = countries_wide, fill = "white", color = "grey30", linewidth = 0.4) +
    geom_spatraster(data = suit_raster) +
    scale_fill_manual(
        name         = "Suitability",
        values       = setNames(c("#F8AFA8", "#74C9E5", "#2E8B57"), labels_vec),
        na.translate = FALSE,
        drop         = FALSE
    ) +
    geom_sf(data = countries_wide, fill = NA, color = "grey30", linewidth = 0.4) +
    geom_point(data = occ_data, aes(x = Longitude, y = Latitude),
               shape = 16, size = 0.8, color = "black", alpha = 0.6) +
    coord_sf(xlim = view_xlim, ylim = view_ylim, expand = FALSE) +
    labs(title = plot_title) +
    annotate("text", x = view_xlim[1] + 1, y = view_ylim[2] - 1,
             label = panel_label, fontface = "bold", size = 5) +
    theme_bw() +
    theme(
        plot.title        = element_text(hjust = 0.5, size = 14, face = "bold"),
        panel.grid        = element_blank(),
        axis.text         = element_blank(),
        axis.ticks        = element_blank(),
        axis.title        = element_blank(),
        legend.position   = c(0.18, 0.25),
        legend.background = element_rect(fill = "white", color = "black", linewidth = 0.3),
        legend.title      = element_text(face = "bold", size = 9),
        legend.text       = element_text(size = 7),
        legend.key.size   = unit(0.4, "cm"),
        plot.background   = element_rect(fill = "white", color = NA),
        panel.background  = element_rect(fill = "white"),
        panel.border      = element_rect(color = "black", linewidth = 0.8)
    )

print(p)

# --------------------------------------------------------------
# 5. Save
# --------------------------------------------------------------
ggsave(paste0(out_prefix, ".png"),  p, width = 10, height = 6, dpi = 600, bg = "white")
ggsave(paste0(out_prefix, ".tiff"), p, width = 10, height = 6, dpi = 600, bg = "white")

cat("Done. Maps written to: ", out_prefix, ".png/.tiff\n", sep = "")
